# Generated by Django 6.0.2 on 2026-02-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('turno', models.CharField(blank=True, max_length=20)),
                ('autoridad', models.CharField(max_length=120)),
                ('deposito', models.CharField(max_length=120)),
                ('motivo', models.TextField(blank=True)),
                ('marca', models.CharField(max_length=60)),
                ('modelo', models.CharField(max_length=60)),
                ('anio', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=40)),
                ('placas', models.CharField(db_index=True, max_length=15)),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('numero_motor', models.CharField(max_length=40)),
                ('tipo_servicio', models.CharField(max_length=30)),
                ('combustible', models.CharField(blank=True, max_length=20)),
                ('kilometraje', models.PositiveIntegerField(default=0)),
                ('estatus_legal', models.CharField(choices=[('En custodia', 'En custodia'), ('Decomisado', 'Decomisado'), ('Siniestrado', 'Siniestrado'), ('Abandonado', 'Abandonado'), ('Liberado', 'Liberado')], default='En custodia', max_length=30)),
                ('oficio', models.CharField(blank=True, max_length=80)),
                ('fecha_oficio', models.DateField(blank=True, null=True)),
                ('titular', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('documento_nombre', models.CharField(blank=True, max_length=180)),
                ('liberado', models.BooleanField(default=False)),
                ('fecha_liberacion', models.DateTimeField(blank=True, null=True)),
                ('autoriza_liberacion', models.CharField(blank=True, max_length=120)),
                ('liberacion_observaciones', models.TextField(blank=True)),
                ('aceite_drenado', models.BooleanField(default=False)),
                ('combustible_drenado', models.BooleanField(default=False)),
                ('anticongelante_drenado', models.BooleanField(default=False)),
                ('sin_objetos_pendientes', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_ingreso', '-id'],
            },
        ),
    ]
