# Generated by Django 6.0.2 on 2026-03-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='grua_direccion',
            field=models.CharField(blank=True, default='', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='grua_motivo',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
