# Generated by Django 6.0.4 on 2026-04-18 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_solicitudcorreccion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap', models.CharField(db_index=True, max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_cuenta', models.CharField(choices=[('DIRECTO', 'Directo'), ('PROSPECTO', 'Prospecto')], max_length=20)),
                ('lista_precios', models.CharField(blank=True, max_length=40)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('zona', models.CharField(blank=True, max_length=60)),
                ('estado', models.CharField(blank=True, max_length=60)),
                ('poblacion', models.CharField(blank=True, max_length=60)),
                ('fecha_registro', models.DateField()),
                ('dias_maximos_entrega', models.PositiveIntegerField(default=0)),
                ('pedido_excede_limite_credito', models.BooleanField(default=False)),
                ('bloquear_cliente_factura_vencida', models.BooleanField(default=False)),
                ('bloqueo_venta_documento_pendiente', models.BooleanField(default=False)),
                ('orden_compra_adquirida', models.BooleanField(default=False)),
                ('permitir_devolucion', models.BooleanField(default=True)),
                ('holgura_dto_pp', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bloqueo_venta', models.BooleanField(default=False)),
                ('bloqueo_cheques_pendientes', models.BooleanField(default=False)),
                ('tomar_inventario', models.BooleanField(default=False)),
                ('modificar_condicion_pago', models.BooleanField(default=False)),
                ('dias_para_fecha_entrega', models.PositiveIntegerField(default=0)),
                ('orden_compra_automatico', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_registro', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(max_length=20, unique=True)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('direccion', models.CharField(blank=True, max_length=180)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['numero_interno'],
            },
        ),
    ]
