# Generated by Django 6.0.4 on 2026-04-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_cliente_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='comprobante_domicilio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='perfil/comprobante/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='perfil/ine/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rfc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='perfil/rfc/'),
        ),
    ]
