# Generated by Django 6.0.2 on 2026-04-21 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_cliente_perfilusuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='comprobante_domicilio_pdf',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/comprobante_domicilio/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ine_pdf',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/ine/'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='rfc_pdf',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/rfc/'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='numero_interno',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SolicitudCorreccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=60)),
                ('valor_nuevo', models.TextField()),
                ('motivo', models.TextField()),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correcciones', to='vehiculos.cliente')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_clientes_resueltas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_clientes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
