# Generated by Django 6.0.2 on 2026-04-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_cliente_address_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='numero_empleado',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
    ]
