# Generated by Django 6.0.2 on 2026-04-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_add_numero_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='contrasena_temporal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
