# Generated by Django 6.0.2 on 2026-05-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0011_alter_cliente_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_visita',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='cliente',
            name='frecuencia_visita',
            field=models.CharField(blank=True, choices=[('mensual', 'Mensual'), ('semanal', 'Semanal'), ('diariamente', 'Diariamente')], max_length=20),
        ),
    ]
