# Generated by Django on 2026-05-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0012_cliente_dias_visita_cliente_frecuencia_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_empleado',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
