# Generated by Django 6.0.2 on 2026-05-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0013_alter_numero_empleado_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='registrado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que realmente registró el cliente (útil para promotores)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_registrados_real', to=settings.AUTH_USER_MODEL),
        ),
    ]
